// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.acme.roogo.domain;

import com.acme.roogo.domain.EntityJpa;
import com.acme.roogo.domain.EntityJpaDataOnDemand;
import com.acme.roogo.domain.Field;
import com.acme.roogo.domain.FieldDataOnDemand;
import com.acme.roogo.domain.RooType;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FieldDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FieldDataOnDemand: @Component;
    
    private Random FieldDataOnDemand.rnd = new SecureRandom();
    
    private List<Field> FieldDataOnDemand.data;
    
    @Autowired
    private EntityJpaDataOnDemand FieldDataOnDemand.entityJpaDataOnDemand;
    
    public Field FieldDataOnDemand.getNewTransientField(int index) {
        Field obj = new Field();
        setEntity(obj, index);
        setFieldName(obj, index);
        setRooType(obj, index);
        return obj;
    }
    
    public void FieldDataOnDemand.setEntity(Field obj, int index) {
        EntityJpa entity = entityJpaDataOnDemand.getRandomEntityJpa();
        obj.setEntity(entity);
    }
    
    public void FieldDataOnDemand.setFieldName(Field obj, int index) {
        String fieldName = "fieldName_" + index;
        obj.setFieldName(fieldName);
    }
    
    public void FieldDataOnDemand.setRooType(Field obj, int index) {
        RooType rooType = RooType.class.getEnumConstants()[0];
        obj.setRooType(rooType);
    }
    
    public Field FieldDataOnDemand.getSpecificField(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Field obj = data.get(index);
        Long id = obj.getId();
        return Field.findField(id);
    }
    
    public Field FieldDataOnDemand.getRandomField() {
        init();
        Field obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Field.findField(id);
    }
    
    public boolean FieldDataOnDemand.modifyField(Field obj) {
        return false;
    }
    
    public void FieldDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Field.findFieldEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Field' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Field>();
        for (int i = 0; i < 10; i++) {
            Field obj = getNewTransientField(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
