// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.acme.roogo.domain;

import com.acme.roogo.domain.Field;
import com.acme.roogo.domain.FieldDataOnDemand;
import com.acme.roogo.domain.FieldIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect FieldIntegrationTest_Roo_IntegrationTest {
    
    declare @type: FieldIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: FieldIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: FieldIntegrationTest: @Transactional;
    
    @Autowired
    private FieldDataOnDemand FieldIntegrationTest.dod;
    
    @Test
    public void FieldIntegrationTest.testCountFields() {
        Assert.assertNotNull("Data on demand for 'Field' failed to initialize correctly", dod.getRandomField());
        long count = Field.countFields();
        Assert.assertTrue("Counter for 'Field' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void FieldIntegrationTest.testFindField() {
        Field obj = dod.getRandomField();
        Assert.assertNotNull("Data on demand for 'Field' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Field' failed to provide an identifier", id);
        obj = Field.findField(id);
        Assert.assertNotNull("Find method for 'Field' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Field' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void FieldIntegrationTest.testFindAllFields() {
        Assert.assertNotNull("Data on demand for 'Field' failed to initialize correctly", dod.getRandomField());
        long count = Field.countFields();
        Assert.assertTrue("Too expensive to perform a find all test for 'Field', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Field> result = Field.findAllFields();
        Assert.assertNotNull("Find all method for 'Field' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Field' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void FieldIntegrationTest.testFindFieldEntries() {
        Assert.assertNotNull("Data on demand for 'Field' failed to initialize correctly", dod.getRandomField());
        long count = Field.countFields();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Field> result = Field.findFieldEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Field' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Field' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void FieldIntegrationTest.testFlush() {
        Field obj = dod.getRandomField();
        Assert.assertNotNull("Data on demand for 'Field' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Field' failed to provide an identifier", id);
        obj = Field.findField(id);
        Assert.assertNotNull("Find method for 'Field' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyField(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Field' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FieldIntegrationTest.testMergeUpdate() {
        Field obj = dod.getRandomField();
        Assert.assertNotNull("Data on demand for 'Field' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Field' failed to provide an identifier", id);
        obj = Field.findField(id);
        boolean modified =  dod.modifyField(obj);
        Integer currentVersion = obj.getVersion();
        Field merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Field' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void FieldIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Field' failed to initialize correctly", dod.getRandomField());
        Field obj = dod.getNewTransientField(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Field' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Field' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Field' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void FieldIntegrationTest.testRemove() {
        Field obj = dod.getRandomField();
        Assert.assertNotNull("Data on demand for 'Field' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Field' failed to provide an identifier", id);
        obj = Field.findField(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Field' with identifier '" + id + "'", Field.findField(id));
    }
    
}
