// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.acme.roogo.domain;

import com.acme.roogo.domain.RooGoUser;
import com.acme.roogo.domain.RooGoUserDataOnDemand;
import com.acme.roogo.domain.RooGoUserIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RooGoUserIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RooGoUserIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RooGoUserIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: RooGoUserIntegrationTest: @Transactional;
    
    @Autowired
    private RooGoUserDataOnDemand RooGoUserIntegrationTest.dod;
    
    @Test
    public void RooGoUserIntegrationTest.testCountRooGoUsers() {
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to initialize correctly", dod.getRandomRooGoUser());
        long count = RooGoUser.countRooGoUsers();
        Assert.assertTrue("Counter for 'RooGoUser' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RooGoUserIntegrationTest.testFindRooGoUser() {
        RooGoUser obj = dod.getRandomRooGoUser();
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to provide an identifier", id);
        obj = RooGoUser.findRooGoUser(id);
        Assert.assertNotNull("Find method for 'RooGoUser' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'RooGoUser' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RooGoUserIntegrationTest.testFindAllRooGoUsers() {
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to initialize correctly", dod.getRandomRooGoUser());
        long count = RooGoUser.countRooGoUsers();
        Assert.assertTrue("Too expensive to perform a find all test for 'RooGoUser', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<RooGoUser> result = RooGoUser.findAllRooGoUsers();
        Assert.assertNotNull("Find all method for 'RooGoUser' illegally returned null", result);
        Assert.assertTrue("Find all method for 'RooGoUser' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RooGoUserIntegrationTest.testFindRooGoUserEntries() {
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to initialize correctly", dod.getRandomRooGoUser());
        long count = RooGoUser.countRooGoUsers();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<RooGoUser> result = RooGoUser.findRooGoUserEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'RooGoUser' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'RooGoUser' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RooGoUserIntegrationTest.testFlush() {
        RooGoUser obj = dod.getRandomRooGoUser();
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to provide an identifier", id);
        obj = RooGoUser.findRooGoUser(id);
        Assert.assertNotNull("Find method for 'RooGoUser' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRooGoUser(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'RooGoUser' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RooGoUserIntegrationTest.testMergeUpdate() {
        RooGoUser obj = dod.getRandomRooGoUser();
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to provide an identifier", id);
        obj = RooGoUser.findRooGoUser(id);
        boolean modified =  dod.modifyRooGoUser(obj);
        Integer currentVersion = obj.getVersion();
        RooGoUser merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'RooGoUser' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RooGoUserIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to initialize correctly", dod.getRandomRooGoUser());
        RooGoUser obj = dod.getNewTransientRooGoUser(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'RooGoUser' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'RooGoUser' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RooGoUserIntegrationTest.testRemove() {
        RooGoUser obj = dod.getRandomRooGoUser();
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'RooGoUser' failed to provide an identifier", id);
        obj = RooGoUser.findRooGoUser(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'RooGoUser' with identifier '" + id + "'", RooGoUser.findRooGoUser(id));
    }
    
}
