// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.acme.roogo.domain;

import com.acme.roogo.domain.RooGoUserDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect RooGoUserDataOnDemand_Roo_Configurable {
    
    declare @type: RooGoUserDataOnDemand: @Configurable;
    
}
