// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.acme.roogo.domain;

import com.acme.roogo.domain.Switch;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Switch_Roo_Configurable {
    
    declare @type: Switch: @Configurable;
    
}
